---
- name: Provision instances
  hosts: localhost
  connection: local
  gather_facts: False
  vars_files:
  - group_vars/all
  tasks:
  - name: Launch instances
    ec2:
      access_key: "{{ ec2_access_key }}"
      secret_key: "{{ ec2_secret_key }}"
      keypair: "{{ ec2_keypair }}"
      group: "{{ ec2_security_group }}"
      type: "{{ ec2_instance_type }}"
      image: "{{ ec2_image }}"
      region: "{{ ec2_region }}"
      instance_tags: 
	    Name: "{{ instance_name }}"
      count: 1
      wait: true
    register: ec2
  - name: Display EC2 instance information
      debug:
        var: ec2	
