---
# tasks file for Gurkirpa-role
- name: Update the apt package cache
  apt:
    update_cache: yes

- name: Install Java 11
  apt:
    name: openjdk-11-jdk
    state: present

- name: Install dependencies
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - curl
    - unzip
- name: Add group "Gurkirpa"
  group:
     name: Gurkirpa
- name: Create user Amanjot and add to Gurkirpa group
  user:
    name: Amanjot
    group: Gurkirpa
    state: present
    shell: /bin/bash
- name: Create a file with custom content
  copy:
    dest: /tmp/guri.txt
    content: |
      This is a sample file created by Amanjot.
      my husband is gurjit singh.
- name: Install MySQL package
  apt:
    name: mysql-server
    state: present
- name: Create MySQL configuration file
  template:
     src: my.cnf.j2
     dest: /etc/mysql/my.cnf
  notify:
  - restart mysql
- name: Start and enable MySQL service
  service:
    name: mysql
    state: started
    enabled: true
